# Pipeline for Develop CI

name: $(Date:yyyyMMdd)$(Rev:r)

trigger:
  branches:
    include:
    - develop
  path:
    exclude:
    - README.md
pr: none

pool:
  name: Hosted VS2017

steps:
- template: Base-Steps.yml
  parameters:
    Version: $(Version-Develop)
    NugetVersion : NugetVersion-Develop
    Publish: 'true'