# Pipeline for Develop CI

name: $(Date:yyyyMMdd)$(Rev:r)

trigger:
- develop

jobs:
- template: Base-job.yml
  parameters:
    Version: $(Version-Job)
    NugetVersion : NugetVersion-Job

- template: Publish-Job.yml