# Pipeline for Master CI

name: $(Date:yyyyMMdd)$(Rev:r)

trigger:
- master

pr: none

pool:
  name: Hosted VS2017

steps:
- template: Base-Steps.yml
  parameters:
    Version: $(Version-Master)
    NugetVersion : NugetVersion-Master
    Publish: 'true'