# Pipeline for Master CI

name: $(Date:yyyyMMdd)$(Rev:r)

trigger:
- develop

jobs:
- template: Base-Job.yml
  parameters:
    Version: $(Version-Master)
    NugetVersion : NugetVersion-Master

jobs:
- template: Publish-Job.yml