# Pipeline for Master PR

name: $(Date:yyyyMMdd)$(Rev:r)

trigger: none
pr:
- master

pool:
  name: Hosted VS2017

steps:
- template: Base-Steps.yml
  parameters:
    Version: $(Version-Master)
    NugetVersion : NugetVersion-Master